{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cea0988e-3bbf-4d15-aed7-b20ea4944427",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "from tkinter import messagebox\n",
    "import random\n",
    "\n",
    "version = \"0.5\"\n",
    "\n",
    "class Hash(Frame):\n",
    "    def __init__(self, master):\n",
    "        Frame.__init__(self, master)\n",
    "\n",
    "        self.areas = None\n",
    "        \n",
    "        self.pinned = None\n",
    "        \n",
    "        self.create_widgets()\n",
    "        \n",
    "        self.start_variable()\n",
    "        \n",
    "        \n",
    "    def start_variable(self):\n",
    "        self.areas = ['one', 'two', 'three',\n",
    "                       'four', 'five', 'six',\n",
    "                       'seven', 'eight', 'nine']\n",
    "        \n",
    "        self.pinned = []\n",
    "        \n",
    "        self.one_show[\"text\"] = \"  \"\n",
    "        self.two_show[\"text\"] = \"  \"\n",
    "        self.three_show[\"text\"] = \"  \"\n",
    "        self.four_show[\"text\"] = \"  \"\n",
    "        self.five_show[\"text\"] = \"  \"\n",
    "        self.six_show[\"text\"] = \"  \"\n",
    "        self.seven_show[\"text\"] = \"  \"\n",
    "        self.eight_show[\"text\"] = \"  \"\n",
    "        self.nine_show[\"text\"] = \"  \"\n",
    "\n",
    "    def get_number(self, n):\n",
    "        win = False\n",
    "        \n",
    "        lose = False\n",
    "        \n",
    "        draw = False\n",
    " \n",
    "        x = n               \n",
    "                    \n",
    "        if x == self.areas[self.get_index(self.areas, x)]:\n",
    "\n",
    "\n",
    "            self.pinned.append(self.areas[self.get_index(self.areas, x)])\n",
    "            \n",
    "            if x == \"one\":\n",
    "                self.one_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"two\":\n",
    "                self.two_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"three\":\n",
    "                self.three_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"four\":\n",
    "                self.four_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"five\":\n",
    "                self.five_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"six\":\n",
    "                self.six_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"seven\":\n",
    "                self.seven_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"eight\":\n",
    "                self.eight_show[\"text\"] = \"X\"\n",
    "            \n",
    "            if x == \"nine\":\n",
    "                self.nine_show[\"text\"] = \"X\"\n",
    "            \n",
    "            self.areas[self.get_index(self.areas, x)] = 0                                \n",
    "                \n",
    "            self.areas[self.random(self.areas, x)] = 1\n",
    "\n",
    "                \n",
    "        else:\n",
    "            messagebox.showinfo(\"Info\",\"Invalid value!\")\n",
    "            \n",
    "            \n",
    "        #player verification:\n",
    "\n",
    "        #horizontal    \n",
    "        if self.areas[0] == 0 and self.areas[1] == 0 and self.areas[2] == 0:\n",
    "            win = True\n",
    "        if self.areas[3] == 0 and self.areas[4] == 0 and self.areas[5] == 0:\n",
    "            win = True\n",
    "        if self.areas[6] == 0 and self.areas[7] == 0 and self.areas[8] == 0:\n",
    "            win = True\n",
    "\n",
    "        #vertical\n",
    "        if self.areas[0] == 0 and self.areas[3] == 0 and self.areas[6] == 0:\n",
    "            win = True\n",
    "        if self.areas[1] == 0 and self.areas[4] == 0 and self.areas[7] == 0:\n",
    "            win = True\n",
    "        if self.areas[2] == 0 and self.areas[5] == 0 and self.areas[8] == 0:\n",
    "            win = True\n",
    "\n",
    "        #diagonal\n",
    "        if self.areas[0] == 0 and self.areas[4] == 0 and self.areas[8] == 0:\n",
    "            win = True\n",
    "        if self.areas[2] == 0 and self.areas[4] == 0 and self.areas[6] == 0:\n",
    "            win = True\n",
    "\n",
    "\n",
    "        #engine verification:\n",
    "\n",
    "        #horizontal    \n",
    "        if self.areas[0] == 1 and self.areas[1] == 1 and self.areas[2] == 1:\n",
    "            lose = True\n",
    "        if self.areas[3] == 1 and self.areas[4] == 1 and self.areas[5] == 1:\n",
    "            lose = True\n",
    "        if self.areas[6] == 1 and self.areas[7] == 1 and self.areas[8] == 1:\n",
    "            lose = True\n",
    "\n",
    "        #vertical\n",
    "        if self.areas[0] == 1 and self.areas[3] == 1 and self.areas[6] == 1:\n",
    "            lose = True\n",
    "        if self.areas[1] == 1 and self.areas[4] == 1 and self.areas[7] == 1:\n",
    "            lose = True\n",
    "        if self.areas[2] == 1 and self.areas[5] == 1 and self.areas[8] == 1:\n",
    "            lose = True\n",
    "\n",
    "        #diagonal\n",
    "        if self.areas[0] == 1 and self.areas[4] == 1 and self.areas[8] == 1:\n",
    "            lose = True\n",
    "        if self.areas[2] == 1 and self.areas[4] == 1 and self.areas[6] == 1:\n",
    "            lose = True\n",
    "        \n",
    "        #draw:       \n",
    "        if lose == False and win == False and len(self.pinned) == 9:\n",
    "            draw = True\n",
    "                           \n",
    "        #notifications:\n",
    "        if win:          \n",
    "            messagebox.showinfo(\"Congrats\",\"YOU WIN!\")\n",
    "            self.start_variable()\n",
    "        if lose:\n",
    "            messagebox.showinfo(\"Info\",\"You lose :(\")\n",
    "            self.start_variable()\n",
    "        if draw:\n",
    "            messagebox.showinfo(\"Info\",\"DRAW\")\n",
    "            self.start_variable()\n",
    "        \n",
    "    def get_index(self, itens, n):     \n",
    "        for i in itens:\n",
    "            if n not in itens:\n",
    "                return -1\n",
    "            else:\n",
    "                return itens.index(n)\n",
    "            \n",
    "    def random(self, itens, x):\n",
    "        while True:\n",
    "            if len(self.pinned) >= 8:\n",
    "                no = itens.index(1)\n",
    "                return no\n",
    "                break\n",
    "            n = random.choice(itens)\n",
    "            if n != x and n != 0 and n != 1:                    \n",
    "                self.pinned.append(n)\n",
    "                \n",
    "                if n == \"one\":\n",
    "                    self.one_show[\"text\"] = \"O\"\n",
    "            \n",
    "                if n == \"two\":\n",
    "                    self.two_show[\"text\"] = \"O\"\n",
    "            \n",
    "                if n == \"three\":\n",
    "                    self.three_show[\"text\"] = \"O\"\n",
    "\n",
    "                if n == \"four\":\n",
    "                    self.four_show[\"text\"] = \"O\"\n",
    "\n",
    "                if n == \"five\":\n",
    "                    self.five_show[\"text\"] = \"O\"\n",
    "\n",
    "                if n == \"six\":\n",
    "                    self.six_show[\"text\"] = \"O\"\n",
    "\n",
    "                if n == \"seven\":\n",
    "                    self.seven_show[\"text\"] = \"O\"\n",
    "\n",
    "                if n == \"eight\":\n",
    "                    self.eight_show[\"text\"] = \"O\"\n",
    "\n",
    "                if n == \"nine\":\n",
    "                    self.nine_show[\"text\"] = \"O\"\n",
    "                \n",
    "                return itens.index(n)\n",
    "                break\n",
    "                \n",
    "        \n",
    "        \n",
    "    def create_widgets(self):\n",
    "        #show game\n",
    "        self.frame1 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame1.grid(row=0)\n",
    "        \n",
    "        self.frame2 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame2.grid(row=0, column=1)\n",
    "        \n",
    "        self.frame3 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame3.grid(row=0, column=2)\n",
    "        \n",
    "        \n",
    "        \n",
    "        self.frame4 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame4.grid(row=1, column=0)\n",
    "        \n",
    "        self.frame5 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame5.grid(row=1, column=1)\n",
    "        \n",
    "        self.frame6 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame6.grid(row=1, column=2)\n",
    "        \n",
    "        \n",
    "        \n",
    "        self.frame7 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame7.grid(row=2, column=0)\n",
    "        \n",
    "        self.frame8 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame8.grid(row=2, column=1)\n",
    "        \n",
    "        self.frame9 = Frame(self, relief = SUNKEN, borderwidth=10)\n",
    "        self.frame9.grid(row=2, column=2)\n",
    "        \n",
    "        \n",
    "        \n",
    "        self.one_show = Label(self.frame1, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.one_show.grid(row=0, column=0, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        self.two_show = Label(self.frame2, font=(\"Verdana\", 12),text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.two_show.grid(row=0, column=1, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        self.three_show = Label(self.frame3, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.three_show.grid(row=0, column=2, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        \n",
    "        \n",
    "        self.four_show = Label(self.frame4, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.four_show.grid(row=1, column=0, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        self.five_show = Label(self.frame5, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.five_show.grid(row=1, column=1, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        self.six_show = Label(self.frame6, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.six_show.grid(row=1, column=2, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        \n",
    "        \n",
    "        self.seven_show = Label(self.frame7, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.seven_show.grid(row=2, column=0, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        self.eight_show = Label(self.frame8, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.eight_show.grid(row=2, column=1, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        self.nine_show = Label(self.frame9, font=(\"Verdana\", 12), text=\"  \", borderwidth=10,padx=20,pady=10)\n",
    "        self.nine_show.grid(row=2, column=2, sticky=\"NWNESWSE\")\n",
    "        \n",
    "        #show buttons\n",
    "        \n",
    "        self.button1 = Button(self.frame1, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"one\"))\n",
    "        self.button1.grid(row=1, column=0)\n",
    "        \n",
    "        self.button2 = Button(self.frame2, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"two\"))\n",
    "        self.button2.grid(row=1, column=1)\n",
    "        \n",
    "        self.button3 = Button(self.frame3, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"three\"))\n",
    "        self.button3.grid(row=1, column=2)\n",
    "        \n",
    "        self.button4 = Button(self.frame4, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"four\"))\n",
    "        self.button4.grid(row=4, column=0)\n",
    "        \n",
    "        self.button5 = Button(self.frame5, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"five\"))\n",
    "        self.button5.grid(row=4, column=1)\n",
    "        \n",
    "        self.button6 = Button(self.frame6, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"six\"))\n",
    "        self.button6.grid(row=4, column=2)\n",
    "        \n",
    "        self.button7 = Button(self.frame7, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"seven\"))\n",
    "        self.button7.grid(row=5, column=0)\n",
    "        \n",
    "        self.button8 = Button(self.frame8, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"eight\"))\n",
    "        self.button8.grid(row=5, column=1)\n",
    "        \n",
    "        self.button9 = Button(self.frame9, font=(\"System\", 6), text=\"x\", padx=10, pady=0, command=lambda: self.get_number(\"nine\"))\n",
    "        self.button9.grid(row=5, column=2)\n",
    "        \n",
    "        #restart\n",
    "        self.frame10 = Frame(self, relief = SUNKEN, borderwidth=2)\n",
    "        self.frame10.grid(row=6, column=1)\n",
    "        \n",
    "        self.button10 = Button(self.frame10,font=(\"System\", 12), text=\"reset\", padx=10, pady=0, command=lambda: self.start_variable())\n",
    "        self.button10.grid(row=6, column=1)\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "hash = Tk()\n",
    "hash.title(f\"Hash Game {version}\")\n",
    "hash.resizable(0, 0)\n",
    "app = Hash(hash).grid()\n",
    "hash.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
